#file: noinspection SpellCheckingInspection
name: Generate APK Debug

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-includes: |
            caches
            notifications
            jdks
            ${{ github.workspace }}/.gradle/configuration-cache

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # temporary disabled
      # - name: Run tests
      #  run: ./gradlew test

      - name: Build apk release
        run: ./gradlew app:assembleDefaultRelease

      - name: Build apk fdroid-release
        run: ./gradlew app:assembleFdroidRelease

      - name: Build apk play-release
        run: ./gradlew app:assemblePlayRelease

      # UPLOAD ARTIFACT SECTION
      # Will be shorter, when https://github.com/actions/upload-artifact/pull/354 will be merged
      # AMMM-default-release
      - name: Upload AMMM-default-arm64-v8a-release
        uses: actions/upload-artifact@v4
        with:
          name: AMMM-default-arm64-v8a-release
          path: app/build/outputs/apk/default/debug/*-default-arm64-v8a-release.apk

      - name: Upload AMMM-default-armeabi-v7a-release
        uses: actions/upload-artifact@v4
        with:
          name: AMMM-default-armeabi-v7a-release
          path: app/build/outputs/apk/default/debug/*-default-armeabi-v7a-release.apk

      - name: Upload AMMM-default-universal-release
        uses: actions/upload-artifact@v4
        with:
          name: AMMM-default-universal-release
          path: app/build/outputs/apk/default/debug/*-default-universal-release.apk

      - name: Upload AMMM-default-x86-release
        uses: actions/upload-artifact@v4
        with:
          name: AMMM-default-x86-release
          path: app/build/outputs/apk/default/debug/*-default-x86-release.apk

      - name: Upload AMMM-default-x86_64-release
        uses: actions/upload-artifact@v4
        with:
          name: AMMM-default-x86_64-release
          path: app/build/outputs/apk/default/debug/*-default-x86_64-release.apk

      - name: Upload AMMM-fdroid-arm64-v8a-release
        uses: actions/upload-artifact@v4
        with:
          name: AMMM-fdroid-arm64-v8a-release
          path: app/build/outputs/apk/fdroid/debug/*-fdroid-arm64-v8a-release.apk

      - name: Upload AMMM-fdroid-armeabi-v7a-release
        uses: actions/upload-artifact@v4
        with:
          name: AMMM-fdroid-armeabi-v7a-release
          path: app/build/outputs/apk/fdroid/debug/*-fdroid-armeabi-v7a-release.apk

      - name: Upload AMMM-fdroid-universal-release
        uses: actions/upload-artifact@v4
        with:
          name: AMMM-fdroid-universal-release
          path: app/build/outputs/apk/fdroid/debug/*-fdroid-universal-release.apk

      - name: Upload AMMM-fdroid-x86-release
        uses: actions/upload-artifact@v4
        with:
          name: AMMM-fdroid-x86-release
          path: app/build/outputs/apk/fdroid/debug/*-fdroid-x86-release.apk

      - name: Upload AMMM-fdroid-x86_64-release
        uses: actions/upload-artifact@v4
        with:
          name: AMMM-fdroid-x86_64-release
          path: app/build/outputs/apk/fdroid/debug/*-fdroid-x86_64-release.apk

      - name: Upload AMMM-play-arm64-v8a-release
        uses: actions/upload-artifact@v4
        with:
          name: AMMM-play-arm64-v8a-release
          path: app/build/outputs/apk/play/debug/*-play-arm64-v8a-release.apk

      - name: Upload AMMM-play-armeabi-v7a-release
        uses: actions/upload-artifact@v4
        with:
          name: AMMM-play-armeabi-v7a-release
          path: app/build/outputs/apk/play/debug/*-play-armeabi-v7a-release.apk

      - name: Upload AMMM-play-universal-release
        uses: actions/upload-artifact@v4
        with:
          name: AMMM-play-universal-release
          path: app/build/outputs/apk/play/debug/*-play-universal-release.apk

      - name: Upload AMMM-play-x86-release
        uses: actions/upload-artifact@v4
        with:
          name: AMMM-play-x86-release
          path: app/build/outputs/apk/play/debug/*-play-x86-release.apk

      - name: Upload AMMM-play-x86_64-release
        uses: actions/upload-artifact@v4
        with:
          name: AMMM-play-x86_64-release
          path: app/build/outputs/apk/play/debug/*-play-x86_64-release.apk
